apiVersion: v1
kind: Service
metadata:
  labels:
    app: httpserver-go
  name: httpserver-go
spec:
  type: ClusterIP
  ports:
    - name: 8888-tcp
      port: 8888
      targetPort: 8888
      protocol: TCP
  selector:
    app: httpserver=go